apiVersion: apps/v1
kind: Deployment
metadata:
  name: wip-service-deployment
  namespace: development
  labels:
    app: wip-service-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: wip-service-app
  template:
    metadata:
      labels:
        apps: wip-service
    spec:
      containers:
      - name: wip-service
        image: wipregistry.azurecr.io/wiserly-inventory-planner:latest
        ports:
        - containerPort: 5000