apiVersion: apps/v1
kind: Deployment
metadata:
  name: wip-service-01
  namespace: development
  labels:
    app: rest-api
spec:
  replicas: 4
  selector:
    matchLabels:
      app: rest-api
  template:
    metadata:
      labels:
        app: rest-api
    spec:
      containers:
        - name: api
          image: wipregistry.azurecr.io/wiserly-inventory-planner:latest  
          ports:
            - containerPort: 8000

