version: '3'

services:
  wiserlyapi:
    build:
      context: ./wiserly_app
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - static_volume:/home/app/web/project/static
      - media_volume:/home/app/web/project/media
    expose:
      - 5000
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust  
    depends_on:
      - wiserlydb
  wiserlydb:
    image: postgres:15-bookworm
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env
  nginx:
    build: ./common_services/nginx
    volumes:
      - static_volume:/home/app/web/project/static
      - media_volume:/home/app/web/project/media
    ports:
      - 1337:80
    depends_on:
      - wiserlyapi

volumes:
  postgres_data_prod:
  static_volume:
  media_volume: