apiVersion: v1
kind: Service
metadata:
  name: wip-service-01
  namespace: development
  # annotations:
  #   service.beta.kubernetes.io/azure-dns-label-name: wiserlyplanner
spec:
  ports:
  - protocol: "TCP"
    port: 8000
    targetPort: 8000
  type: LoadBalancer    
  selector:
    app: wip-service