apiVersion: v1
kind: Service
metadata:
  name: wip-service-deployment
  namespace: development
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: wiserlyonline
spec:
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: LoadBalancer    
  selector:
    apps: wip-service-deployment