apiVersion: v1
kind: Service
metadata:
  name: wip-service-deployment
  namespace: development
  service.beta.kubernetes.io/azure-dns-label-name: wiserlyonline
spec:
  ports:
    - name: https
      port: 80
  type: LoadBalancer    
  selector:
    apps: wip-service-deployment