web:
  replicas: 2
  image: wiserly-inventory-planner
  tag: init
  args:
    - '--bind'
    - '0.0.0.0'
    - 'manage:app'
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 200m
job:
  image: wiserly-inventory-planner
  tag: init
  command:
    - python3
  args:
    - cli.py
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 200m